# Generated by Django 5.1.1 on 2024-10-24 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="poster",
        ),
    ]
