# Generated by Django 5.1.1 on 2024-10-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_remove_event_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Statut"),
        ),
    ]
