# Generated by Django 5.1.1 on 2024-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_guest_participation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.TextField(null=True, verbose_name="Prix"),
        ),
        migrations.AddField(
            model_name="participation",
            name="is_pending",
            field=models.BooleanField(
                default=True, verbose_name="En attente de validation"
            ),
        ),
    ]
