# Generated by Django 5.1.1 on 2024-10-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("conference", "Conférence"),
                    ("workshop", "Atelier"),
                    ("cultural", "Culturel"),
                    ("ftour", "Ftour"),
                    ("competition", "Compétition"),
                    ("charity", "Caritatif"),
                    ("talent_show", "Eigsi Got Talent"),
                    ("integration_day", "Journée d'intégration"),
                    ("other", "Autres"),
                ],
                max_length=20,
                verbose_name="Type d'évènement",
            ),
        ),
    ]
