# Generated by Django 5.1.1 on 2024-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poster",
            field=models.FileField(default="", upload_to="", verbose_name="poster"),
        ),
    ]
