# Generated by Django 5.1.1 on 2024-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_event_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="poster",
            field=models.FileField(upload_to="", verbose_name="poster"),
        ),
    ]
