# Generated by Django 5.1.1 on 2024-10-24 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_event_poster"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
